### ISSUE TITLE
Need tool to view layer attribute table

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#109]
For spatial data there are two main data displays:

1. View the spatial data shapes for the layer on a map.
2. View the attributes for the shapes in an attribute table window.  The attribute table should have a column heading with attribute names and each row will match a feature in the layer.

QGIS and GeoProcessor allow viewing each of the above.  The InfoMapper needs a tool that is accessible for each vector layer.  Using the tool will display the attribute table.  This should use an NgPrime table (I recommend reaching out to Catherine).  The table should include a scroll bar without paging.   TSTool has a good table design.   The table can be in a popup, ideally that can be moved.

**Comment by Nightsphere** [comment]
This issue is similar to #223, and will be closed as the base functionality has been completed.
