### ISSUE TITLE
Zooming out sometimes causes polygon layer to not draw?

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#114]
In the process of testing, I zoomed out to multiple states where the Poudre was not in the visible area.  When I panned back the layer was not visible.  I tried to recreate but could not.  I remember seeing this previously but thought it might be due to other issues.

Keep an eye on this.  The issue is a placeholder.

**Comment by Nightsphere** [comment]
This had to do with giving a style property of the polygon as a string instead of a number. After updating and parsing the string to a number, the issue has not happened. We can open again if there are more problems in the future. Closing the issue.
