### ISSUE TITLE
Polygons sometimes randomly don't redraw

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#123]
Sometimes polygons won't draw when panning.  I found the following Leaflet repository issue [GeoJSON Polygons Disappearing and Reappearing on Pan](https://github.com/Leaflet/Leaflet/issues/6075) that indicates that maybe the weight is being set as a string instead of a number and using a number fixes the problem.  Need to check how the layer view property is being handled and in general need to make sure values are properly cast.

**Comment by smalers** [comment]
I saw this behavior again today.  I zoomed out and turned layers on and off.  When I pressed the home icon the Poudre basin outline drew as follows:

![image](https://user-images.githubusercontent.com/6448274/90327291-6e0d5780-df4f-11ea-9634-5fe32df24d46.png)

**Comment by smalers** [comment]
I've seen this again recently.  I don't know if is related to the zooming, or possibly turning layer on/off.  See the original issue post for a possible solution.  Any random behavior is undesirable.

**Comment by Nightsphere** [comment]
All weights are now a number, and should hopefully take care of the redrawing issues. Will close after more testing.

**Comment by Nightsphere** [comment]
This is looking good; we can reopen if other issue present themselves. Closing the issue.
