### ISSUE TITLE
Symbol image in legend needs more intelligence

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#134]
**This is lower priority than other issues**

Using an image for symbol needs more intelligent sizing in the legend.  The goal should be to show images in the legend at similar size.  For example, decide that a 32x32 pixel size (or some size) is a good size for legend image.  If the symbol image is square, then setting the width and height of the image for the legend would result in new distortion.  However, if the image is not square, setting the width and height could distort the image.  Maybe there is a library to figure out the actual image size so it can be scaled appropriately for the legend?

The current breweries legend image is about half the size it needs to be.

**Comment by Nightsphere** [comment]
This has been taken care of in the closed Issue #135 and #141. Closing this issue.
