### ISSUE TITLE
Symbol image on map need to be positioned

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#135]
The default marker seems to center on the coordinate.  This may be counter to typical behavior.  For example, such an image may make more sense if the "pointer end" of the symbol is on the coordinate rather than the middle of the image.  The DWR Division 1 office is an example where the symbol seems to be out of place when viewing the whole basin, and becomes more accurate when zooming in.    I need information about what properties could be set to control the behavior and can then provide direction.  For TSTool, a symbol property can be specified to position the symbol `UpperLeft`, `Centered`, etc. The math to shift the image is then done internally rather than forcing the user to do it.

If the marker has no "pointer", then it can probably be centered on the coordinate, which makes sense for the default behavior.

Need to evaluate what is typically done with markers.

**Comment by smalers** [comment]
Using the TSTool graphing specification, I recommend the following for symbol position:

UpperRight, Right, LowerRight, Below, LowerLeft, Left, UpperLeft, Above, Center

The default is Center.  For pushpin type icons, that point down, `Above` would be the typical setting.

**Comment by smalers** [comment]
I found the following article, which seems helpful:  [https://stackoverflow.com/questions/22706270/leafletjs-custom-marker-position-not-right](https://stackoverflow.com/questions/22706270/leafletjs-custom-marker-position-not-right)

**Comment by Nightsphere** [comment]
Users can now choose where to position an image in the InfoMapper by supplying the image's pixel dimensions in the `symbolImage` or `builtinSymbolImage` file path like so:

`/img/default-marker_25x41.png` or `/img/default-marker-25x41.png`

Additionally, a lowercase or uppercase x, X will work.

A new geoLayerSymbol property has also been created for this implementation, name `imageAnchorPoint`. This takes 7 different positions that can be given as follows:

1. `Bottom`
2. `Center`
3. `UpperLeft`
4. `Top`
5. `UpperRight`
6. `LowerRight`
7. `LowerLeft`
8. The default positioning, as determined by Leaflet, is `UpperLeft`. This can still be explicitly given as well, but if image dimensions are given and the previous 7 property values are not, `UpperLeft` will be the position for InfoMapper by default.

**Comment by smalers** [comment]
I updated the Poudre Basin Information application to use this code.  Initially none of the images showed up.  It was my understanding that default position handling would occur in this case.  It is mainly an issue when new images are added but the filename is not changed to show the size.  This could be a common case for someone that is not careful.  I'm going to update the Poudre application to change the filenames as indicated in previous issue comments.  If that works, then this is a minor issue.

**Comment by smalers** [comment]
Also need to add `Left` and `Right`.

I have added the documentation to the GeoProcessor GeoMap Project appendix.

**Comment by Nightsphere** [comment]
`Left` and `Right` have both been added as image positions. The default has also been updated so that if no `imageAnchorPoint` is given, the default `UpperLeft` will be used. Any other bugs or updates can be separate issues; closing this one.
