### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#146]
**Now is not the time to make changes but I'm adding this as an issue at a lower priority so that it can be handled in the future.**

After doing some work with the InfoMapper, I think it would be cleaner if the product name is InfoMapper (no space) and repository name were `owf-app-infomapper-ng` (no dash).  Removing the dash simplifies some things and allows other repositories to more easily use the product name.  For example, the Poudre "dashboard" repository could be renamed to `owf-app-infomapper-poudre` (or similar) and other implementations could also use similar name.  Then there would be a consistent pattern.

Various folder names could also be changed to remove the dash.    Documentation would also need to be updated.

**Comment by Nightsphere** [comment]
The repo has been successfully renamed, with all instances to my knowledge of the two words combined into one. If any more sneak in, other issues will be made in the future. Closing the issue.
