### ISSUE TITLE
Showdown does not handle internal links and other formatting issues

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#155]
I added a release notes page to the Poudre application.  The Markdown conversion does not seem to handle internal links.  Is this an addition to default behavior?

```
[link name](#section-in-document)

# Section in document
```

Also, it would be nice if the table had lines to separate columns.  See the source:

[Poudre Basin Information release notes](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/blob/master/web/content-pages/release-notes.md).

**Comment by Nightsphere** [comment]
Now that we can control what CSS is used from issue #224, formatting issue can be taken care of through adding more css. The external links option has also been turned on for Showdown in the constructor, taking care of that problem. Closing this issue.
