### ISSUE TITLE
Add css file to override defaults

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#164]
The InfoMapper css needs to be configurable for an implementation, such as the StateMod dataset viewer, in order to customize fonts and other styles.  Given that it is tricky to check for file existence, maybe we should implement a default css file, which can be empty if no overrides, but should always exist.  Or, maybe it is OK if it does not exist, but I assume that could cause a console message.  The filename could be something like:

```
app/css/app.css
```

Once we establish the file, documentation should be created.  Maybe there are other options, but it would be something similar to this.

**Comment by smalers** [comment]
Actually, I see that the default app has a `style` folder.  Maybe we just need to discuss how that is being used and document.

**Comment by Nightsphere** [comment]
The InfoMapper contains the top-level `styles.css` file that can override fonts and other styling throughout the app. How it is being used has been added to the InfoMapper README file. Closing this issue.
