### ISSUE TITLE
Mouseover popups are flashy

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#170]
The mouseover popup can get into a state of flashiness.  It appears that the popup for a feature is perhaps "fighting" with the popup when not on a feature.  This was not an issue when the most recent popup remained on top of the map (but that was a problem because it took up a lot of space).

I think if something could be done to only show one popup at a time based on state then it would be OK.

**Comment by Nightsphere** [comment]
This issue the same as issue #238, but the newer issue has more updated info about the problem. Closing this issue.
