### ISSUE TITLE
Need minimal default configuration for deployment

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#171]
It is good that the default application configuration is available, especially for a new InfoMapper user.  However, as the files with that application grow, it adds to the size of deployed application.  It would be useful to have a minimal `app-config.json` file and related files that can be copied into the `app` folder, and remove all other files.  For example:

* minimal `app-default/app-config.json`  - no need for demos
* minimal `app-default/content-pages/home.md` page that says `If you are seeing this page there is  an error in the InfoMapper configuration.  Contact info@openwaterfoundation.org or the known support contact for this website.
* maybe put in a folder `app-default-minimal`

Then I can update the Poudre and other upload scripts to strip out the default application before deploying to the public web.  This will reduce the size of deployments.  We can of course leave the default application in if it makes sense for some deployments.

**Comment by Nightsphere** [comment]
After looking into what can and can't stay in the `app-default` directory, the following directories/files can be removed from a script before deploying:

```json
content-pages/about-the-project.md
data-maps/
data-ts/
```

Most of the files are in `data-maps`, so this should help with reducing the size.

The `app-config.json` being used for the minimal deployment right now is the following:

```json
{
  "title": "Info Mapper Default",
  "homePage": "/content-pages/home.md",
  "favicon": "/img/coloradoDNR.ico",
  "version": "1.0.0 (2020-12-01)",
  "mainMenu": [
    {
      "id": "MapsExample",
      "name": "Maps",
      "align": "left",
      "tooltip": "Example of a Main Menu Tab",
      "menus": [
        {
          "name": "Map Example 1",
          "enabled": "false",
          "mapProject": "data-maps/map-configuration-files/line-geometry-maps.json",
          "tooltip": "Display Map Example 1"
        },
        {
          "name": "Map Example 2",
          "enabled": "false",
          "mapProject": "data-maps/map-configuration-files/polygon-geometry-maps.json",
          "tooltip": "Display Map Example 2"
        },
        {
          "name": "Map Example 3",
          "enabled": "false",
          "mapProject": "data-maps/map-configuration-files/point-geometry-maps.json",
          "tooltip": "Display Map Example 3"
        }
      ]
    },
    {
      "name": "Resources",
      "align": "left",
      "id": "ResourcesExample",
      "tooltip": "Show default resources",
      "menus": [
        {
          "name": "InfoMapper User Documentation",
          "action": "externalLink",
          "url": "http://software.openwaterfoundation.org/infomapper/latest/doc-user/",
          "tooltip": "Follow link to InfoMapper User Documentation"
        }
      ]
    }
  ]
}
```

**Comment by smalers** [comment]
I added the InfoMapper script `build-util/clean-dist-for-deployment.sh` to clean the `dist/` folder for deployment.  This script should be modified as necessary by InfoMapper lead developer to keep the deployment clean.  This script is called by the Poudre Basin Information `build-util/copy-to-owf-amazon-s3.sh` script.  I also modified the `home.md` file to hopefully be as clear as possible.  I did test the new script with Poudre Basin Information deployment and it worked.

Here are additional comments:

1. How does the `app-default` file as mentioned in the above comment allow development to occur with the `app-default/` test data?  I was thinking that the `clean-dist-for-deployment.sh` script would replace the more verbose dev/test configuration file with a minimal file such as mentioned above.  This would allow development to occur as needed and deployment to use a minimal configuration file.  Otherwise, isn't the development configuration file going to be NOT in the repository?
2. The favicon should be the OWF icon such as from the Poudre Basin Information files.  The `coloradoDNR.ico` file does not need to be in the repository since it can be added for a specific application.
3. Application configuration file should use `InfoMapper` (no space).
4. I recommend adding README.md files in the `app-default` folders to explain the folders and files.

**Comment by smalers** [comment]
Based on discussion, this is what I understand will happen (or similar):

1. The `app-default/app-config.json` file in the repo will be the one used for development and testing.
2. A `app-default/app-config-minimal.json` file (similar to that shown in this issue) will be used for deployment.
3. The `build-util/clean-dist-for-deployment.sh` script will copy the `app-config-minimal.json` file to `app-config.json` in `dist` folder for deployment.

This allows development to commit configuration to the repo, but use a minimal configuration for deployment.

**Comment by Nightsphere** [comment]
Yes that's how I understood it as well. I'm currently creating the main README file for the `app-default/` folder to also help explain this, and can be added to in the future for further explanations. It, along with the other changes listed above, will be pushed within the next hour.

**Comment by Nightsphere** [comment]
After this new push, the minimal configuration set up will be detected if:

1. An `app-config.json` file does not exist in **assets/app/** and
2. An `app-config.json` file does not exist in **assets/app-default/** and
3. If `app-config-minimal.json` does exist in the **assets/app-default/**

As mentioned above, the only files needed to make the minimal version run is the `app-config-minimal.json` file and **content-pages/home.md**. So the folders/files that can be deleted with a script for deployment are:
```
content-pages/about-the-project.md
data-maps/
data-ts/
```

The minimal config set up has now been implemented, so I'm closing this issue.
