### ISSUE TITLE
ChartJS improve legend

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#174]
The ChartJS graph currently puts the legend where a title is.  Is it possible to reposition the legend to under the graph similar to TSTool?

Also, the legend shows a rectangle.  Can the legend use a line with symbol, similar to what is shown on the graph?

**Comment by Nightsphere** [comment]
I'm about to push with some new legend updates. It has been moved to the bottom now. As for
showing a line, Chart.js has pushed back on that, and I'll need to do some more digging and talking
to Sofia to see what she thinks about it.

**Comment by Nightsphere** [comment]
Chart.js has been removed from the InfoMapper in favor of Plotly, a more robust charting package. Closing this issue.
