### ISSUE TITLE
Multiple times series with differing dates don't display correctly

### ISSUE THREAD

**Issue by Nightsphere** [OpenWaterFoundation/owf-app-infomapper-ng#186]
Make a check and add code that will correctly show multiple time series on a graph even if they span different amounts of time.
Right now both are shown with regards to only one of the time series, so the subsequent times on the remaining time series
are incorrect.

**Comment by smalers** [comment]
Different periods of record is a very common situation and needs to be gracefully handled.   Ideally the charting package is smart enough to allow time series with different periods to be displayed.  However, it may be required to format data in a "grid" array where all cells have some value (or missing value indicator).  It may also be the case that time series have different interval, such as trying to plot monthly and daily data on the same graph. TSTool handles all of these situations but the web application code will need to be implemented.

Based on Josh's comment, I'm assuming that ChartJS is not handling the time series alignment properly.   I recommend the following:

1. To support different charting packages in a general way, maybe it makes sense to create an interface with methods like the following, which will allow determining what features a package has.  An implementation class would then be called by the InfoMapper to determine whether to generate an exception or handle the data.  If the driver does not handle some functionality, then work-around logic may be possible.
* `handlesDifferentPeriods` - does the charting package handle different time series periods?
* `handlesDifferentIntervals` - does the charting package handle different time series intervals?
2. There is Java utility code that can help.  For example, `TSUtil` class methods: `areIntervalsSame`, `getDataLimits`, and `getPeriodFromTS`.
3. It is necessary to loop through the data.  If the code to transfer data to chart package is by dataset, then the dates to process must be retrieved from the dataset.  If the charting package requires alignment, use the `DateTime` from the `getPeriodFromTS` utility code above.   If alignment is not required, use the `getDate1` and `getDate2` functions.  If alignment is required, use the maximum period dates to loop.
4. The `getDataValue` method will return a missing value if a requested `DateTime` is outside the time series' data period. This value can be converted to the charting package missing value.

**Comment by Nightsphere** [comment]
The new push is up now and takes care of the glaring issues. There are certainly more things to consider however, before this
issue can be closed.

**Comment by Nightsphere** [comment]
This has been working for a while now. Closing the issue.
