### ISSUE TITLE
Make an official release

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#190]
We need to draw the line on the "dev" release and make an official release.  Then we can start doing more typical releases and increment the version number accordingly.  It would be nice to move to a 1.x.x release that is fairly stable.  I typically only go into a longer "dev" mode when I know there is going to be a period of avoiding an official release.  I often won't even do hot fixes on the master branch but will tell people to use the latest dev release if they need to.

Below are things I think need to be done to get to an official release.  This can then be used with the StateMod dataset viewer and other projects, rather than a zero release.  I believe that issues exist for items listed below.

1. Close issues that have been resolved.  If a reasonable amount of testing has occurred, close the issue.  We can reopen later if necessary.   Resolve as many minor/trivial issues as possible so they don't clutter the backlog.  Split issues if necessary so parts can be resolved.  I'm hoping that at least 25% of the issues can be closed.
2. Time series viewing:
     1. Ensure that time series with different periods re handled properly.
     2. Display legend for each time series (not main title for legend) so that time series can be differentiated.
     3. Better hover and zooming would be ideal (need plotly) but can live without if don't have time to resolve.
3. Fix the legend view group handling.   This is a glaring issue given that all other major functionality bugs have been cleared up.  If this is going to be a problem, we need to discuss the design.
3. Enable Google Analytics so that we can track usage.  See issue #144.
4. Would like to hide the MapBox key.   I don't know how many hits we are going to get but we don't want people racking up hits on our account key.  I'd also like to make sure we are using an appropriate account, not a former employee that happened to set up the account.  See issue #99.
5. Need to add license information in ***About***.  See issue #66 for language for InfoMapper.  I need to decide what to do about other content but will probably use Creative Commons.

**Comment by Nightsphere** [comment]
I believe the core criteria for this has been met, and the release of 1.0.0 was done a few weeks ago. Other issues can be created going into the future. Closing this issue.
