### ISSUE TITLE
Plotly: configure zoom so only x-axis zooms by default

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#216]
The plotly graphing tool by default allows users to zoom in X and Y axis.  This generally causes more problems than goof for typical time series graphs.  Sofia figured out how configure plotly zoom tool to zoom in the x axis and this should be implemented in the InfoMapper.  Changing the behavior in the InfoMpper is pretty important for usability.

If someone zooms in and the time series shows near the bottom of the graph, we still need a tool to allow zooming in both directions.  I'll work with Sofia to figure out a good approach in the Angular demo application and we can then transfer back to the InfoMapper.

**Comment by Nightsphere** [comment]
Plotly graphs will now zoom on the x axis by default.

**Comment by Nightsphere** [comment]
The main functionality of this issue is done. We will keep the ability to zoom in by both x and y axes in mind moving forward. Closing the issue.
