### ISSUE TITLE
Clicking on info button displays documentation twice

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#220]
Clicking on a layer's info button twice displays two documentation pop-ups.  The first has content and the second is blank.  The behavior should probably be one of the following:

1. Second click does nothing.
2. Second click closes the documentation.

I'm not sure what the typical UI behavior is in this case, but the first case is a reasonable behavior.  If a second copy must be displayed for some reason, it should at least be populated.

**Comment by Nightsphere** [comment]
Started trying to work on it, but ran into some issues. I can disable the button from being clicked, but only after the Dialog has been closed. So, while the popup Dialog is open, you can still open the same Dialog over and over again, which defeats the purpose of trying to fix this. I'll keep working on this over time.

**Comment by Nightsphere** [comment]
The Window Manager has now been updated to the point that it will stop more than one of the same dialog from opening at once. This includes all kebab menus, Leaflet buttons, and the map info button. Closing this issue.
