### ISSUE TITLE
Add support for web feature service

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#227]
Some spatial data layers are available as web feature services (WFS), which are vector services that can be queried for a map extent.  For example, see data for the following:

* [National Interagency Fire Center](https://data-nifc.opendata.arcgis.com/)
    + Select Current Wildfire Perimeters (but any of the datasets may be useful)
    + Select Wildfire Perimiters
    + Select ***API Explorer*** or the ***APIs*** list.

What we want to do is NOT download the nationwide GeoJSON because it is large.  Instead, we want to query an extent, such as Colorado, the Poudre Basin, or maybe one of these with additional buffer, and retrieve vector features of interest.  An issue is, if the map is interacted with or redrawn, do queries occur repetitively and what is the performance hit.

Need to figure out what support Leaflet has for Web Feature Service.  Maybe Esri provides a Leaflet plugin?

**Comment by smalers** [comment]
It is going to be important to know what type of service given that thee is an Esri service and open standard service.  See the following.  Because many layers that we deal with come from Esri servers, getting that working is probably a higher priority, but it is not clear how robust the solution is.

* [Ersi service leaflet](https://esri.github.io/esri-leaflet/api-reference/services/map-service.html)
* [Esri tutorial](https://esri.github.io/esri-leaflet/tutorials/working-with-feature-layers.html)
* [WFS article at Penn State ](https://www.e-education.psu.edu/geog585/node/779)
* [Article from 2015](https://gis.stackexchange.com/questions/64406/getting-wfs-data-from-geoserver-into-leaflet)

**Comment by Nightsphere** [comment]
Here is a link to the url I'm using to create the feature layer, with `/query` added to the end. It is very similar to the Colorado DNR REST API website where you can build the query to what you want.

https://services3.arcgis.com/T4QMspbfLg3qTGWY/ArcGIS/rest/services/Public_Wildfire_Perimeters_View/FeatureServer/0/query

At first this was completely Greek to me, as I had no idea what each of those do. I found the API docs here:

https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm

This helped, but I'm still not sure what would be used to query specific bounds or boundary box.

**Comment by smalers** [comment]
It seems that there are at least 3 permutations on WFS, and we need to be precise in our documentation:

1. OGC WFS - we need to understand how the specification defines URLs and returned data and how handled in GeoProcessor/Leaflet/InfoMapper
2. Esri map service - does it match OGC WFS? or is it something else?
3. Something in between, for example OGC WFS + GeoJSON as a return format

See this [GitHub issue](https://github.com/Esri/arcgis-to-geojson-utils/issues/21) illustrating how Esri development seems to lag GeoJSON specification... obviously we are trying to figure out something that works.

Some major issues to document are:

1. For open data portals, which of the above is used and how id it specified in GeoProcessor commands?
2. Is it possible to constrain the query to a region, such as State of Colorado boundary so that the service returns a reasonable amount of data?  If so, what is the URL?
3. Is the GeoJSON that comes back valid and works with GeoProcessor and InfoMapper?  If so, GeoJSON can be requested and may be easier to deal with.  If GeoJSON works with GeoProcessor but not InfoMapper, then we may not be able to use the GeoJSON URL in maps.

**Comment by Nightsphere** [comment]
Here is the esri link example that is working with the Info Mapper now:

https://services3.arcgis.com/T4QMspbfLg3qTGWY/ArcGIS/rest/services/Public_Wildfire_Perimeters_View/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=-109.05%2C36.99%2C-102.05%2C41&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelContains&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=

This is used as the `sourcePath` with the sourceFormat being `GeoJSON`. This is showing all properties of the each feature as a regular Leaflet geoJson layer.

**Comment by smalers** [comment]
The above URL is long and contains default values.  The following works as a GeoProcessor command.  A GeoJSON file is returned

```
    # The following uses a minimual number of parameters, shown without URL encoding:
    # - where=1=1 (why needed?)
    # - geometryType=esriGeometryEnvelope (used to specify rectangle for query)
    # - geometry=xmin,xmax,ymin,ymax  (where x is longitude and y is latitude, must URL-encode commas using %2C)
    # - inSR=4326 (input CRS, for the bounding box, default is that of the layer on the server)
    # - returnGeometry=true (default, to return geometries)
    # - f=pgeojson (pretty GeoJSON)
    # - f=geojson (GeoJSON)
    # - outfields=* (return all attributes)
    # - geometryPrecision=5 (digits for coordinates)
    # - outSR (seems to default to 4326 for GeoJSON output format)
    # - multipatchOption (is this needed?)
    # - spatialRel=esriSpatialRelContains (how the envelope is used to select features)
   
 ReadGeoLayerFromGeoJSON(InputFile="https://services3.arcgis.com/T4QMspbfLg3qTGWY/ArcGIS/rest/services/Public_Wildfire_Perimeters_View/FeatureServer/0/query?geometry=-109.05%2C36.99%2C-102.05%2C41&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelContains&outFields=*&geometryPrecision=5&f=geojson",GeoLayerID="WildfirePerimetersLayer",Name="Colorado Wildfire Perimiters",Description="Colorado wildfire perimeters web service")
```

**Comment by smalers** [comment]
Given that the FWS returns GeoJSON, there is no reason to support the other formats.  Keep this open a bit to see how the wildfires layer performs.

Still need to get the Esri background layers working though.

**Comment by smalers** [comment]
I am going to close this issue.  We have a workable solution with Esri WFS using GeoJSON.  I have now documented in the GeoProcessor documentation enough to record our experience on this.  I think the lead on OGC FWS support can occur through GeoProcessor first, and when figured out, add to InfoMapper if necessary.   Close this issue.
