### ISSUE TITLE
Feedback on info icons

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#229]
I'm filling out documentation for the Poudre maps so there is at least basic content for each page.  I have the following feedback:

1. The Info button for map is a bit hard to aim for.  The arrow to minimize the panel seems to overlap?  I use the tooltip to make sure I am aiming at the correct thing, but that slows the user down.
2. Change the tool tip for layer to "Click to view layer documentation", which is consistent with other tooltips.  The concept of "layer view" is internal and just calling it "layer" for users is OK.
3. The Poudre Basin Information menu for ***Basin Entities / Environment - Instream Flow Reaches*** has a long map name that causes the information icon to wrap.  Need to figure out a solution such as use smaller font (but not for all?), use "...", let the text overwrite the icon?  I don't want this to disrupt all the other layer names that are short.   I can probably shorted by getting rid of "Basin".

![image](https://user-images.githubusercontent.com/6448274/90112297-08318d80-dd0d-11ea-94d4-3ced4143e572.png)

**Comment by Nightsphere** [comment]
All 3 points have been taken care of, at least for now. Leaving the issue open if other unforeseen problems arise because of this new push.

**Comment by Nightsphere** [comment]
Double checked and did more testing that info icons will display correctly, even when long geoMap, layerView, etc. names are given. Closing the issue.
