### ISSUE TITLE
Long document header causes documentation popup scrollbar to be in wrong position

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#231]
If the `#` header in a markdown documentation popup is long, it wraps and the scroll bar is shifted away from the right side of the popup.  I don't know if this is related to Showdown newline issues.  Using different CSS that make the fonts smaller could also help.   Actually, I'm not sure that the header length has anything to do with it because I see the issue with short headers also.   See the layer documentation for the following:

* [Poudre Environmental Organizations](http://poudre.openwaterfoundation.org/0.2.1/#/map/entities-envorg)

![image](https://user-images.githubusercontent.com/6448274/90112149-db7d7600-dd0c-11ea-84ce-01047e9accdf.png)

**Comment by Nightsphere** [comment]
This has been fixed using CSS. Closing the issue.
