### ISSUE TITLE
Layer legend description is not using space on the right

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#240]
The layer descriptions appear to be not using the space on the far right.  I assume because the space is held for icons.   For now, tools/icons are envisioned to be made available at the layer level, but not the legend/description level.  Hopefully the layout can be reworked so that layer descriptions can use the space.  This will avoid some wrapping and shorten the legend vertically.

**Comment by Nightsphere** [comment]
Updated the side bar so that the description goes all the way to the right, whether a doc button is present or not. Fixed the placement of the switch button. Closing this issue.
