### ISSUE TITLE
Need to be able to configure radio buttons for polygon layers in a group

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#242]
I added a [Political - Legislative Districts](http://poudre.openwaterfoundation.org/0.3.0/#/map/entities-legislative) map to the Poudre Basin Information website.  There are layer views for House and Senate districts for 2011 and there will be new districts this year or next.  Because the districts cover the entire state and use transparency, there is confusion if more than one layer is on at the same time.  The map configuration file specification supports a design to indicate if the layer views in a group should only allow one on at a time, similar to background layers.  I need confirmation that this has been implemented for other than background and I can try.

I'm going to to have to figure out how to handle federal and county legislative districts, with similar issues.

**Comment by smalers** [comment]
I found an example on an Esri site that illustrates this requirement:

[Water Districts](https://gisweb.fcgov.com/HTML5Viewer/index.html?Viewer=Utility%20Districts)

![image](https://user-images.githubusercontent.com/6448274/96213411-34000800-0f36-11eb-97bb-253aa1c7bf64.png)

**Comment by smalers** [comment]
I previously documented [GeoLayerViewGroup](http://software.openwaterfoundation.org/geoprocessor/latest/doc-user/appendix-geomapproject/geomapproject/#geolayerviewgroup) properties that describe how this might be configured.

**Comment by Nightsphere** [comment]
Two major pushes were merged with new properties being supported. The `selectBehavior` property has now been implemented for a geoLayerViewGroup in the geoMap. When non-existent or set to `Any`, any and all layers in the group can be turned off and on at will.

When set to `Single`, at most one layer can be turned on at a time. By default, the top most layer in the group will be toggled on, but can be any layer if a user specifies for each layer in the group to be turned off except for the desired layer. All layers can also be turned off as well. Clicking on a toggled off layer while another in the group is being shown will toggle off the shown layer and display the clicked layer.

The solution to this issue also needed Issue #148 to be completed, which was done as well. Closing this issue.
