### ISSUE TITLE
Evaluate how to convert epoch time to date/time string for GeoJSON

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#245]
The wildfire perimeter layer read from FWS is showing times as UNIX epoch integers wheres before it seemed to be a formatted date/time string.  It is therefore difficult to know when the data were updated.

It may be possible to do an SQL query to the service, to convert to a date/time string using an SQL function. 
 However, that may involve selecting each of the fields manually in the SQL, which is cumbersome since we don't control the data and attributes may change.  It may be possible to check the type of the value returned so that the SQL is generic, but that may take some work.

Another option would be to auto-detect attributes with `date`, `time`, or `date/time` in the attribute name, and large integer value.  If found, the epoch time could be converted to a date/time in UTC by default, or even convert to computer's local time.  This is probably a pretty safe assumption.  To be safe, the popup could show as a new attribute with appropriate name.

Later, when we enhance the popup formatting (another issue), we can put more energy into this.

**Comment by Nightsphere** [comment]
The date conversion has now been updated for both mouseover and clicking on a feature. Closing this issue.
