### ISSUE TITLE
Hover popup with wide text causes the popup to be very wide

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#248]
Some of the hover popups show very wide text, for example URLs to websites.  See the [Poudre Water Providers](http://poudre.openwaterfoundation.org/latest/#/map/entities-water-providers) and mouse over Fort Collins.  I recommend treating similar to the click popup, where URL was wrapped or use "...".

If we implement an attribute table viewer, then the table column could be resized to view the wide output, or save to a file.

**Comment by smalers** [comment]
This weekend I added a Basin Entities / Physical - Basins map and also monitored the wildfires. Some popups are being negatively impacted by long strings.  Similar to what you did on the URLs, I think you need to build in some line breaks or "..." for long attribute strings.  As you are working on formatting dates, please deal with this also.  The popups should behave nicely regardless of the width of data.  Adding a feature to view attributes in a table or export attributes could help users get to the information.

**Comment by Nightsphere** [comment]
Using issue #245, a max length to each property line has been implemented and can be updated if different desired lengths want/need to be used instead. The foundation of this issue has been fixed, closing the issue.
