### ISSUE TITLE
Add layer view group property expandedInitial or similar

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#249]
Now that more background layers are being added to maps, the legend can show a large number.  Although the layers are at the bottom and users don't need to scroll them, the longer list will cause a scrollbar to appear more often in the legend.  Because the legend for background layers does not add a lot of visible information and the icon tool allows selecting a background layer, perhaps we can add a property on the layer view group `expandedInitial=false`, which could be used to compress the layer view group.  This might also be used for some other groups.

**Comment by Nightsphere** [comment]
I have added the `expandedInitial` property to the background geoLayerViewGroup. If not present, by default, the background layers will be hidden. If false, the background layers will also be hidden. If true, the layers will be shown like how they were in the past.

**Comment by Nightsphere** [comment]
I believe the core functionality has been added, closing the issue.
