### ISSUE TITLE
Add icon in main menus for content page

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#255]
Most menus have an icon on the left to help identify what will happen.  Currently, content pages do not have an icon, which causes the menu items to be offset from the other items.  I suggest adding an icon that represents documentation, for example, from [Material icons](https://material.io/resources/icons/?style=baseline) for `menu_book`,  Or maybe optionally allow an icon to be specified with an application configuration `icon` property, consistent with how other icons are specified.

Or, at a minimum, position the content pages so that a blank area is shown so the menu item words line up.  This is similar to desktop applications where the left side of menus is reserved for an icon shortcut.

The initial action on this issue is to decide a default icon for content pages and implementing configurable icon can come later.

**Comment by Nightsphere** [comment]
A default icon has been implemented and will show up on a content page menu drop down.

**Comment by Nightsphere** [comment]
The icon seems to be working well. Closing the issue.
