### ISSUE TITLE
Extra horizontal lines in legend

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#259]
The legend has horizontal lines at top and at bottom, which are not needed and take up space.  The lines are in particular not needed when a layer group only contains one layer.  It is OK to have the horizontal line between layers when multiple lines are in a group.

**Comment by Nightsphere** [comment]
As stated in the commit message, dividers between layers in the side bar are now conditional, and will only add them if they are between more than one layer, saving more space. Closing the issue.
