### ISSUE TITLE
Blank map due to bad configuration - need better error messages

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#260]
I'm creating a new map and seeing a blank map.  I'll figure it out but I wish I could be more efficient tracking down errors.  For example, the error mentions a possibly bad path but provides no clue as to the property or path so I can only assume.  If the error only gives the map configuration file name, that is not much help.  I suggest that bad configurations should be tested and improve console messages.  See below.

![image](https://user-images.githubusercontent.com/6448274/91502161-a6ccfb00-e884-11ea-8743-73132f950a7d.png)

**Comment by Nightsphere** [comment]
This issue will be closed, and if other error message updates need to be added, another issue will be opened in the future.
