### ISSUE TITLE
Showdown css is not being applied to content pages?

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#261]
I started a new InfoMapper project for rivers of the US, which is the top-level site that will provide national information and navigation to more specific implementations.  It does not seem like the Showdown CSS is being applied to the content pages, such as release notes.

**Comment by Nightsphere** [comment]
Updated the creation of Content Pages using Showdown, so the CSS file that styles the documentation button will also affect Content pages. Closing the issue.
