### ISSUE TITLE
Generalize the default application information

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#262]
The InfoMapper uses "Poudre" in its home page, etc.  I think the language should be generalized to "default application configuration" or something similar.  It is OK that data and the zoom level correspond to the Poudre River Basin in Colorado, but we don't want people to get confused that the InfoMapper default app is a production website.

I also still need some guidance on trimming out default app files so that the bare minimum is distributed in production systems.  We don't want to bloat up every copy of websites.

**Comment by Nightsphere** [comment]
Dozens of files have been deleted so that a skeleton configuration is displayed to the user. I won't close this yet, and wait if Steve will have any feedback for smaller changes/updates.

**Comment by smalers** [comment]
My main comment is there are two levels of cleanup:

1. Making sure that the repo does not have a bunch of temporary files used in one-off testing.  The repo should only contain the necessary software and configuration files for deployment, and testing files used with automated testing (cypress).
2. Assuming that some files such as `src/assets/app-default` are in the repo for testing, etc. and support development, do I need to run a script after `ng build` to remove test files, etc. from the `dist` folder before deploying to the cloud?  The goal is to have as small a footprint as possible.

**Comment by Nightsphere** [comment]
The information for the script to remove necessary files when deployed can be viewed on the closed Issue #171. The generalized app-default files have changed their description from Poudre Portal based to InfoMapper based. Closing the issue.
