### ISSUE TITLE
Esri FWS have cap on number of features returned?

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#263]
**This is not high priority for Poudre but does impact national map products.**

I recently added a national map on OWF's website in order to highlight the basins where InfoMapper has been implemented, and to explore design issues with national datasets.  Background tile servers should not be a problem.  However, I am concerned about other vector and raster layers that when read are not constrained by the viewable map extent.  For example, I added a wildfires map using the same FWS URL as used for the [Poudre Basin Information map](http://poudre.openwaterfoundation.org/latest/#/map/current-wildfires) but with larger envelope extent.  The [national wildfires map](http://rivers.openwaterfoundation.org/us/country/latest/#/map/current-wildfires) is understandably slower to load, but it also seems to leave out some wildfire features, such as the Williams Fork fire.  This will likely be dynamic as fires are added and dropped.  I am assuming that there is a cap on the number of features returned and multiple requests may be required to get a full list of features.  Therefore I have the following questions/comments:

1. How can Esri FWS server that returns GeoJSON be queried multiple times to create a complete result?
2. Is there already a Leaflet solution built or do we need to write code?
3. I don't think it makes sense to reload the layer when zooming, based on requerying for the current extent.  This will probably be complicated and result in bad performance.  Maybe it makes sense to have scale-dependent layers, for example to show image tile overlays at large scale and vector/feature data when zoomed in.  I don't think such features are obvious on many GIS websites and lead to a lot of confusion.  If we go this route we need to do it well.  We'd have to add properties on the layer view for the scale at which the layer is visible and make it obvious in the legend.  This is the type of thing that may be needed large-scale maps.

**Comment by smalers** [comment]
I tried to set `resultType=standard` based on the [API documentation](https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm).  It seemed to initially help with the [national wildfires map](http://rivers.openwaterfoundation.org/us/country/latest/#/map/current-wildfires) but then features are missing again.  I recommend the following:

1. Print a console message to indicate how many features are in the layer from FWS.  If it is a round number like 1000 or 2000, then it is likely that a cap is being hit.  Then more work would be needed to figure out how to work around this, such as querying the FWS metadata to understand cap limits.
2. Bigger picture, it would be good to have an information tool that can be used for a layer to indicate metadata such as the number of features and list of attributes.  This could be used for troubleshooting and would be the first step towards implementing an attribute table viewer.

**Comment by Nightsphere** [comment]
I've added a log with how many features each map layer has, so that can be viewed for the time being. The link for the geojson is https://opendata.arcgis.com/datasets/5da472c6d27b4b67970acc7b5044c862_0.geojson. This should return the entire dataset with around 1,230 feature/fires. This can be plus or minus 10; the data updates every 5 minutes.

**Comment by smalers** [comment]
I'm going to close this.  Using the GeoJSON dataset solved the problem.  I also [documented in GeoProcessor](http://software.openwaterfoundation.org/geoprocessor/latest/doc-user/spatial-data-format-ref/EsriWFS/EsriWFS/) with enough detail to help understand the issue.  If more functionality is needed, a new issue can be added.
