### ISSUE TITLE
Evaluate hamburger menu for map, group, and layer

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#267]
Other issues are focusing on specific new requirements, for example being able to view layer metadata and attribute table.   We have added prominent icons for information and settings but cannot clutter up the UI with many more tools.  One option is to add tools along the left side, but this can be confusing because the user must coordinate the selection of a layer with selection of a tool.  A context-sensitive approach is to provide tool access with the object of interest (map, group, layer).  One way this could be done is to add a hamburger menu as stack of lines or dots (vertical line of dots would take less width), located where the info icon is.  When clicked on, a menu could be shown with appropriate tools or actions.  The following are candidates for the menu:

* Save image (for map)
* Metadata - show number of features, source URL, etc.
* Zoom to layer - figure out layer extent and zoom to it with some buffer
* View attribute table - doing as a popup using clusterize or built-in Angular table might be a good start
* Save data - for example, would save the original GeoJSON as local file
* See QGIS and Esri tools for more

I think having the settings in this menu may be OK since not often used.  I think having the info as an icon is still useful because we are trying to provide quick access to information and the info pages are formatted as content that people may want to get to with one click.

If a prototype looks OK, we can try to use as some of the other issues items are implemented.

**Comment by Nightsphere** [comment]
Research has been done for this, and we have figured out that the official name for the 3 vertical dots button is called a kebab
menu (and the 3 horizontal dots is called meatballs). It seems to be working well, and looking okay on the InfoMapper.

The implementation of more of these options in the kebab menu can be opened up as issues in the future. Closing this issue.
