### ISSUE TITLE
Legend polygon fill should match that rendered on the map

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#271]
Polygons drawn in the legend should matched those on the map, including fill color and transparency.  Currently the symbol in the legend does not always match.

**Comment by Nightsphere** [comment]
The push for this has been made, and should take care of the legend icons displaying exactly as the map polygon `color`, `fillColor`,
`fillOpacity` and `weight`. If any of these are not given in a classification file, a default will be used. Closing the issue.
