### ISSUE TITLE
Can coordinate information always show 6 digits?

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#272]
The coordinate display does not always show the same number of digits.  It would be nice if the format was always 6 digits after the decimal, which provides appropriate detail for high-resolution work.  People can choose to truncate the coordinates if they don't want that detail.  Always formatting to 6 would provide consistency.  Is this possible?

**Comment by Nightsphere** [comment]
The existing code in the InfoMapper was using built-in Leaflet code that had a bug in rounding numbers. It has been changed to `toFixed(6)` which will return 6 numbers no matter what. Closing the issue.
