### ISSUE TITLE
Dialog title is incorrect for information popups

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#273]
I updated the Poudre application to the latest InfoMapper commit.  Josh implemented a title in the upper title area for Data Table.  It looks like this is also being used for popup info dialogs, but the left side is empty and the right side says "Data Table", which is wrong.  I suggest the following:

* For the left side of the dash, use the map, layer group, or layer name.
* For the right side of the dash, use `Information` or `Data Table`.
* I'm not sure about graphs, but TSTool uses `Graph` so that would be a start.  However, I'm not sure about the left side.  Having a blank title as before would be OK for now until this is more clear.  We'll have to keep an eye on this if other visualizations are implemented.

**Comment by Nightsphere** [comment]
Each dialog opened will either display the geoMap, geoLayerViewGroup, or geoLayerView name on the left and Information on the right, or the geoLayerView name on the left and Data Table on the right. For right now, graph dialog's will not contain a title in the gray div. Closing this issue.
