### ISSUE TITLE
Attribute table links point to wrong organizations.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#275]
**I am going to start entering attribute table issues separately so that they are easier to manage.  Issue #223 can be split up as new issues so it can be closed out.**

I updated the [Municipal Water Privers](https://github.com/OpenWaterFoundation/owf-data-co-municipal-water-providers/blob/master/data/Colorado-Municipal-Water-Providers.geojson) dataset so that almost all entities have websites with URLs.  I fixed so the URLs all start with `http` or `https`.  When I view the layer data table, the link points to a different website than the row of interest.  This is a major issue and needs to be resolved so that I can push out a Poudre update.

**Comment by Nightsphere** [comment]
The push and merge for this issue has been completed. I will wait for a bit more testing by Steve before I close the issue.

**Comment by Nightsphere** [comment]
The links have been behaving like they should over the past couple days on quite a few attribute tables in development and in the Poudre Basin website. This issue can be reopened if need be, but I'm closing this issue.
