### ISSUE TITLE
Popup information dialogs are blank

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#281]
The deployed Poudre application is showing blank window when map and layer information popup is tried.  Basically, no documentation seems to be working.  There are no console messages so this seems to be a logic problem.  **This needs to be fixed ASAP.**  This is the type of bug and functionality that might be good for automated testing since the use case.  Apparently neither Josh or I tested this and therefore did not notice the issue.

**Comment by Nightsphere** [comment]
This had to do with a changeDetection strategy I implemented for application performance. The solution was a double-edged sword, and I am actively researching how to deal with the performance in a more stable way. I have pushed the reverted code again, and the doc dialogs should be working as normal again. I'll create another issue for the pipe strategy I've been looking up. Closing this issue.
