### ISSUE TITLE
Content pages do not scroll when page size is too small to fit content

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#287]
Content pages do not display completely and no vertical scrollbar is shown, thereby cutting off the bottom of the content.  A vertical scrollbar needs to be visible when this situation occurs, and ideally not be shown otherwise.

**Comment by Nightsphere** [comment]
A new push has been made with the changes that will add a scroll bar to the Content Page if needed, and will not show it if not needed. Closing the issue.
