### ISSUE TITLE
Updating from remote repo shows a schema validation error

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#289]
This might be something to put in developer documentation in a troubleshooting section.

I did a pull of the latest InfoMapper into Poudre Basin Information.  When I did `ng serve --open` I get: 

```
sam (master) infomapper $ ng serve --open
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(allowedCommonJsDependencies).
```

Next I did `npm install` and was able to run it.  Maybe developer documentation needs several lists of errors that can be fixed with common actions, such as doing `npm install`, restarting `ng serve`, etc.

**Comment by Nightsphere** [comment]
This is an old Angular version issue (about 5 major versions), which has been updated and fixed by Google. Closing the issue.
