### ISSUE TITLE
Time series graph and table are repeating last value

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#298]
The graph and data table are showing the 2049 value for Weld county as redundant with the 2048 value.  The  actual 2049 value is `696870.0000`.  It looks like perhaps an iterator is stopping while using the previous iteration's value.

Once we implement the ***Save*** feature it will hopefully be possible to compare the original input file with the saved result to confirm that values are as expected.

**Comment by Nightsphere** [comment]
The iterator used for DateValue files now goes up to the last value to correctly display it on the data table. It was not doing so before. Closing the issue.
