### ISSUE TITLE
Add Save button for time series data table

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#300]
A ***Save*** button is needed on time series table to save the table.  The main use case is to save a csv so people can read into or paste into Excel.  The following are technical considerations:

1. The time series may come from different files and sources.  Therefore, it may be easiest to output from the data input to the table, not the original time series files.  This is actually consistent with TSTool because once read into the time series, the original file is not carried around or output again.
2. When saving, create a simple CSV file with headings similar to the table view.   See the [TSTool `WriteDelimitedFile.writeTimeSeries` method](https://github.com/OpenCDSS/cdss-lib-processor-ts-java/blob/master/src/rti/tscommandprocessor/commands/delimited/WriteDelimitedFile_Command.java) for example.  Missing data values need to be handled as well as an output precision.  For now only save as `csv`.   Can add other formats later if necessary.
3. If someone wants to save the original input file, they can do so by accessing the URL to the asset - see [issue 299](https://github.com/OpenWaterFoundation/owf-app-infomapper-ng/issues/299).
4. Use a ***Save*** button at the bottom of the dialog next to  ***Close*** in standard Windows order.
5. Can ***Ctrl-s*** also be supported?
6. A file chooser should list default filename, maybe the TSAlias or TSID with `csv` if one time series and `time-series.csv` if multiple time series?  The user can override.
7. Behavior should be similar to how browser saves the source for web page.
8. If time series have different intervals and are shown in multiple tables, similar to TSTool, need more complex logic.  Displaying tables with different time series intervals has not yet been implemented (software needs to check this and warn if attempted).  Maybe add that as a separate issue.  To start, don't allow saving multiple time series that have different intervals.
9. Once save is enabled, it can be used with Angular Cypress end to end testing.  Talk to Elizabeth about the work she has been doing to understand how to do.

**Comment by Nightsphere** [comment]
The push has been made for this issue. I will wait to close until more testing has been done.

**Comment by smalers** [comment]
Here is my feedback based on using with the StateMod dataset viewer:

1. I described the data access on [this page](http://opencdss.openwaterfoundation.org/datasets/colorado/2015/#/content-page/hist-data).  The first option in the table is workable and I can document in a way that lists more examples.
2. For the time series data table, I suggest that we add a property to the popup configuration file such as the following.  The save file will be associated with the button, which is associated with specific time series so it should be possible to define appropriately.  If it is possible to use a file selector with extension to select the file, this can be revisited, but that could be complicated.

```
{
  "id" : "reservoir-popup-config",
  "name": "Reservoir popup configuration",
  "description":  "List main attributes and provide buttons to graph time series.",
  "layerAttributes" : {
    "include" : [ "*" ],
    "exclude" : [],
    "formats": []
  },
  "actions": [
      {
        "label" : "Targets",
        "action" : "displayTimeSeries",
        "resourcePath" : "graphs/reservoir-Target-graph-config.json",
        "saveFile" : "${featureAttribute:StateModStationId}-targets.csv"
      },
```

**Comment by smalers** [comment]
Here are more comments based on the latest version:

1. Can a tooltip be added to the Download button with "Save time series data as csv file"
2. If `saveFile` property is not found, use `timeseries.csv` as default name.  If the property indicated in `saveFile` is undefined, also default to `timeseries.csv`.   I had an error in configuration and the file ended up being `undefined.csv` (bad attribute) and then `undefined.txt` (missing `}`).

**Comment by Nightsphere** [comment]
The new push has been merged that contains the small feedback changes and updates for Issues #265, #278, #300 and #302.

**Comment by smalers** [comment]
My bad.  Change the tooltip to `Download time series data as csv file` to be consistent.

**Comment by Nightsphere** [comment]
I believe the last of the formatting has been taken care of, and the tooltip has been updated. Testing was done in Excel and TSTool. Closing the issue.
