### ISSUE TITLE
Add layer properties popup.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#302]
It would be useful to have a ***Properties*** tool for each layer similar to ***Data Table*** (list menus alphabetically unless there is a reason not to).  This could be  simple popup with information about the layer, such as some of the information from the GeoMapProject file and other useful information.  Maybe it would be possible to provide a link that could be pasted in a URL to retrieve the original file, similar to the links that I tried [here](http://opencdss.openwaterfoundation.org/datasets/colorado/2015/#/content-page/hist-data).   That way the user would know the link without having to guess.  This would help developers and users locate data and understand why save files have the names defaulted.

I also wonder if we could/should add a ***Download*** menu to trigger a save of the layer file.  Thinking this through, I wonder if we should use the word ***Download*** rather than ***Save*** on other dialogs since the user is not saving anything to a website.  We might allow configurations to be saved to a website at some point and ***Save*** might make more sense then.  Let's discuss.  I found an [old article](https://ux.stackexchange.com/questions/61137/good-wording-to-indicate-export-and-download-action) and more searching could be done.

**Comment by Nightsphere** [comment]
The initial push for this issue has been merged. All Save buttons have been converted to Download as well, as per research done on similar buttons from other websites.

**Comment by smalers** [comment]
This functionality works.  New issues can be added for more layer tools.  Close the issue.
