### ISSUE TITLE
Graph popup with long title causes scrollbar to be shown

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#303]
Sometimes the graph title is long and wraps, which causes a scrollbar to be shown and buttons are not visible unless the window is scrolled.  I'm not sure if this can be fixed gracefully, such as making the graph area slightly smaller to fit the longer title without scrolling.  See the example below:

[http://opencdss.openwaterfoundation.org/datasets/colorado/2015/#/map/cm2015-historical](http://opencdss.openwaterfoundation.org/datasets/colorado/2015/#/map/cm2015-historical)

![image](https://user-images.githubusercontent.com/6448274/95296372-eb5d9600-0835-11eb-9c70-06c0cb19b911.png)

**Comment by Nightsphere** [comment]
I believe this has been taken care of. I'll wait to close until tested further in the Poudre Basin Information website

**Comment by smalers** [comment]
This seems to be working.  Close the issue.
