### ISSUE TITLE
Change popup configuration to use downloadFile

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#306]
We changed the use of `save` to `download` but the popup configuration still uses `saveFile`.  I recommend changing that to `downloadFile` to be consistent.  I noticed this while updating the InfoMapper documentation to include the latest.  This needs to be updated ASAP before deploying some public website updates.

**Comment by smalers** [comment]
This has been implemented.  Close the issue.

**Comment by smalers** [comment]
I updated the issue.  It should be `downloadFile`.  I think this was implemented but it does not seem to work when the value is a file without the `.function()` modifiers.  For example, the following always results in the download file defaulting to `timeseries.csv`:

```
"downloadFile" : "${featureAttribute:StateModStationId}-Available_Flow.csv"
```

**Comment by Nightsphere** [comment]
The push for this has been merged, and has been working. Closing the issue.
