### ISSUE TITLE
Change highlighted features reset from data table to layer kebab menu

### ISSUE THREAD

**Issue by Nightsphere** [OpenWaterFoundation/owf-app-infomapper-ng#308]
Right now when a dialog is closed, all highlighted features on the layer is reset and they go away. Update the code so that they stay when the dialog is closed, and move the option to turn them off into the layer kebab menu on the side bar.

**Comment by Nightsphere** [comment]
Updated the code so that when something is searched for in the data table and the features highlighted, they will stay highlighted when the dialog is closed. The user will have to use the layer kebab menu in the side bar and select **Clear Selection**

**Comment by smalers** [comment]
This is working as stated.  Close the issue.
