### ISSUE TITLE
Consider moving information access to kebab menus

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#309]
**This is not labeled as high priority because there are other things to do.  However, if it is simple and improves the user experience, it might make sense to do sooner.**

Now that the kebab menu has been implemented, it might make sense to move the "info" functionality to the kebab menu.  Some thoughts:

1. Having as an icon is convenient but clutters up the UI.   People can only handle 4-7 things at a time.
2. If it is in the menu, should the ***Information*** menu item always be shown and be disabled if no documentation?  Or if no documentation should the menu item not even be shown.
3. A kebab menu would need to be added at every level that icon was present before, which is probably a useful thing.
4. The icon can still be used in the menu to make it easy to find.
5. I'm wondering whether the info icon should continue to be shown at the map level to make it easy to read overall information about the map, but for layer put into a kebab menu.  This reflects that the map does not actually have many UI components but layers have several things going on.  Layer group could also use a kebab, mainly to hide the settings, which don't do anything much right now and need to be redesigned.

Once this and other menu issues are implemented, maybe we should revisit the settings/gear and decide how to make it more useful.

**Comment by Nightsphere** [comment]
The update is up now, with the removal of the information button at the layer level, and the adding of it to the kebab menu. If no docPath property is given, the button will be disabled. For now I have left the info button alone in the map and layer view menus.

**Comment by Nightsphere** [comment]
Another update has removed the info circle button for the layerViewGroup and changed it to its own kebab menu. The info circle now only appears at the map level. I believe this issue has been successfully updated. Closing the issue.
