### ISSUE TITLE
Graph has formatting issues

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#310]
**This is pretty important.  I need to have this working to finish a project.**

I updated the Poudre application's population data.  The InfoMapper has a number of issues.  I am providing data files separately.

1. The `Color` graph configuration property does not seem to be getting picked up.  I need to update TSTool to support `#ffffff` hex notation but currently it uses the C/Java `0xffffff` notation.  The InfoMapper should handle both.
2. The legend position is off.  It needs to calculate size based on font size and number of items.
3. The top line should draw for the full period.  In other words, there should be points on top of the line.

![image](https://user-images.githubusercontent.com/6448274/96578234-157d7200-1292-11eb-8110-0238eb459f8f.png)

![image](https://user-images.githubusercontent.com/6448274/96578648-bff59500-1292-11eb-91e6-3069f40fefbf.png)

**Comment by Nightsphere** [comment]
C and Java hex notation is now usable for graph coloring, and the legend positioning is now more robust.

**Comment by smalers** [comment]
These issues are resolved.  I'm closing the issue.
