### ISSUE TITLE
Change popupConfigPath property to eventConfigPath 

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#314]
Now that we are enabling the hover event configuration, the property `popupConfigPath` is too specific.  I recommend changing that to `eventConfigPath`.  The filename that is referenced can have `hover` or `click` in it to differentiate.  I recommend supporting the old `popupConfigPath` syntax for awhile but write a warning to the console.

The hover event file syntax will be the same as click, but there will be no supported actions yet.  We can add actions later, such as advanced highlighting, such as highlighting upstream river basins when hovering over a downstream basin.

See also issue #306, which is similar.

**Comment by Nightsphere** [comment]
I added the `eventConfigPath` property, but will still support the `popupConfigPath` with the warning message like you suggested. It will work the same way as the click event, with include and exclude supported for filtering out the desired properties.

**Comment by smalers** [comment]
I updated the [GeoProcessor documentation](http://software.openwaterfoundation.org/geoprocessor/latest/doc-user/appendix-geomapproject/geomapproject/#geolayervieweventhandler) and [InfoMapper documentation](http://software.openwaterfoundation.org/infomapper/latest/doc-user/appendix-install/map-event-config-file/#event-configuration-file-properties).  However, I was not able to get the new include/exclude features working.  I'm not sure what is wrong.  All attributes are shown even though the event handlers are defined for hover and click.

**Comment by Nightsphere** [comment]
The new push has been merged. Auto-generated values should now be taken care of. The only thing not implemented right now is a wildcard as part of a string, e.g. `"b*"`  will not work right now. An asterisk by itself however `"*"` will work.

**Comment by smalers** [comment]
The warning message is incorrect.  It says `propertyConfigPath` instead of `popupConfigPath`.

**Comment by Nightsphere** [comment]
The `eventConfigPath` property has been implemented, and has been working. Issue #315 has more feedback issues to work on, so I will close this issue.
