### ISSUE TITLE
'visible' property for sub-menu in application configuration is not recognized

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#322]
Need functionality of `visible` property in application configuration file for sub-menus.  This is convenient for disabling menus that are not ready for public site but want to test in development.

**Comment by Nightsphere** [comment]
After double checking and testing, I realized this has already been implemented for both menus and sub-menus. `visible = true` in the app-config file will not show either. Closing the issue.
