### ISSUE TITLE
Legend text wrap issues on long text

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#324]
The legend text wraps on long text and overflows into the next item.  See the example for counties below.  In most cases, maps should not be configured to have long legend text so hopefully it can be avoided in most cases.  Need to have some type of solution for the formatting.

![image](https://user-images.githubusercontent.com/6448274/97762482-4ea5b580-1ace-11eb-8e5f-982e6f1fa588.png)

**Comment by Nightsphere** [comment]
This is the same as the newly created #402. Closing this issue.
