### ISSUE TITLE
Error displaying GeoTIF layer

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#334]
I am trying to add a GeoTIF layer to the Colorado Agricultural Water Transfer website.  Below is the GeoProcessor commands to add the layer:

```
# = = = = = = = = = =
# Municipality raster data:  read layers and add to a layer view group.
# - copy from the repository that contains WWR data
# GeoLayerViewGroupID: MunicipalitiesRasterGroup
#
AddGeoLayerViewGroupToGeoMap(GeoLayerViewGroupID="MunicipalitiesRasterGroup",Name="Colorado Municipalities (Raster)",Description="Colorado Municipality area derived from polygons",InsertPosition="Top")
#
CopyFile(SourceFile="${WWRRepoFolder}/Rasters/Municipality.tif",DestinationFile="layers/Municipality.tif")
ReadRasterGeoLayerFromFile(InputFile="layers/Municipality.tif",GeoLayerID="MunicipalitiesRasterLayer",Name="Colorado Municipalities (Raster)",Description="Colorado Municipality area derived from polygons")
AddGeoLayerViewToGeoMap(GeoLayerID="MunicipalitiesRasterLayer",GeoLayerViewID="MunicipalitiesRasterLayerView",Name="Colorado Municipalities (Raster)",Description="Colorado Municipality area derived from polygons",Properties="docPath:'layers/Municipality.md'")
```

The layer does show up in the legend but it replaces the normal background layers, does not display, and the slider and kebab menu are not working.  Need to figure out what is going on.

![image](https://user-images.githubusercontent.com/6448274/99583286-80f55500-29a0-11eb-975a-efe19ca6f1b9.png)

![image](https://user-images.githubusercontent.com/6448274/99583114-48ee1200-29a0-11eb-827a-cf1d349b284c.png)

**Comment by smalers** [comment]
I uploaded to the cloud:  [http://coagtransfer.openwaterfoundation.org/0.3.0/#/map/data-municipalities](http://coagtransfer.openwaterfoundation.org/0.3.0/#/map/data-municipalities)

**Comment by Nightsphere** [comment]
This seems to be working now on `0.3.0`. I'm not sure if Steve pushed again with new changes, but there are no errors anymore for the raster.

**Comment by Nightsphere** [comment]
This has been resolved in the previous commit and merge. Closing the issue.
