### ISSUE TITLE
Raster layer is not drawn when map is first displayed

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#335]
The [Colorado Agricultural Water Transfer](http://coagtransfer.openwaterfoundation.org/0.3.0/#/map/data-municipalities) application has raster layers for ***Supporting Data / Municipal - Municipalities*** and ***Supporting Data / Water Supply - Water Providers***.  The maps seem to display the raster layers OK.  However, the layer does not show when the map is initially displayed.  I had to toggle the layer off and on to get it to draw.  **I just updated to Amazon and sometimes there is latency (1 hour?) to see the latest version.  Run in an incognito window.**

This is high priority because I want to show someone the website.

**Comment by Nightsphere** [comment]
The changes for this issue have been merged, and a raster layers initial z-Index has been changed so that it isn't covered by any of the basemaps. This should take care of the displaying of the layer on the map.

**Comment by Nightsphere** [comment]
This seems to be fixed now, and is now showing the layer for the Municipalities map. It can be reopened if we find it hasn't been completely resolved. Closing the issue.
