### ISSUE TITLE
Need a way to mouse over raster cell and see the corresponding value

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#336]
**This is a high priority to be able to use raster data effectively.**

Now that raster layers are being used in maps, we need a way to inspect the value of a raster cell and display in the hover and click popups. Each raster layer contains a single value (although may support rasters with multiple bands later).  Because multiple raster layers may overlap, with see-through opacity, it would be useful to drill down through each and show the corresponding value.  The hover and click popups could show something like:

```
Raster layer name:  abc
Cell value:  123 (label)
Raster layer name:  abc
Cell value:  456 (label)
```

where the layer name comes from the layer view, the cell value is from the raster at the mouse location, and the label is the `label` value from the classification file.

**Comment by Nightsphere** [comment]
The functionality for this has been implemented, and `Raster layer name` has been changed to `Raster`. Closing the issue.
