### ISSUE TITLE
Raster does not load, possibly due to projection issue

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#337]
I am trying to add a GeoTIF  and am getting the following error.  Perhaps the raster file is in a project that needs to be converted to Leaflet CRS and don't have the code enabled to do the reprojection?  I'll provide the image file via email.  Maybe check the CRS of the layer and output a console message like "InfoMapper requires raster layers to use epsg:xxxx CRS, ABC layer is using espg:yyyy".  That way it can be addressed during map setup.

![image](https://user-images.githubusercontent.com/6448274/99782612-a1bfc680-2ad6-11eb-8115-c2c25e1f64b3.png)

**Comment by smalers** [comment]
I enhanced the GeoProcessor to convert raster CRS to EPSG:4326 so that I can display on the map.  I am changing this issue to medium priority.  Just need to improve the warning to indicate what CRS is supported.

**Comment by Nightsphere** [comment]
An error message has been given if the CRS of the raster layer given is not EPSG:4326. There is a question I still have about this issue that I'll follow up with Steve during our next check-in.

**Comment by Nightsphere** [comment]
I figured out my question, and the error message will explain that the raster layer will not be displayed if EPSG:4326 is not the CRS for the raster. It also explicitly lists EPSG:4326 as the only supported CRS. Closing this issue.
