### ISSUE TITLE
Handle nodata value in raster popups

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#342]
The raster hover event handler is working but shows a large negative number for no data value (approximately `-3.39e+38`).  This is probably the biggest negative 32-bit floating point number.  The data type is Float32 for the raster even through integer values are stored in the cell.   I need to check on how GeoProcessor/PyQGIS handles data type for each band when manipulating the raster.

The hover popup should display as `Cell value:  no data`  in this case.  I recommend writing a utility function somewhere like `boolean isCellValueMissing(value)`.  The no data value is stored with the raster so need to decide how to handle that.  In general, avoid many function calls to return the same value.

As for detecting the value, it may be necessary to bracket the value, which is what TSTool does, something like:

```
nodataValue = raster.getNoDataValue();
boolean isCellValueMissing(value) {
    // For the following need to handle case where trying to offset can't be done because value is already at end 
   // of language limit.  Not sure if trying to go outside will throw an exception or just assign to the limiting value.
    // The limiting value is OK because the check below uses >= and <=.
    nodataValueMin = noDataValue - .000001
    nodataValueMax = nodataValue + .000001
    if ( (value => nodataValueMin) && (value <= nodataValueMax) ) {
       return true;
   }
   else {
       return false;
   }
}
```

**Comment by smalers** [comment]
The [Poudre Basin Information](http://poudre.openwaterfoundation.org/1.0.0/#/map/current-wildfires) wildfire map hover popup is not showing the cell data value.  The configuration file is below.

```
{
  "id" : "cameron-peak-sbs-raster-event-config",
  "name": "Hover and click event handlers for cameron-peak-sbs-raster.tif",
  "description":  "Display only important user-understandable attributes.",
  "layerAttributes" : {
    "include" : [ "*" ],
    "exclude" : [],
    "formats": []
  },
  "actions": [
  ]
}
```

**Comment by Nightsphere** [comment]
The error handling has been updated for the `classificationAttribute`, and will display an appropriate warning/error message to help debug. Closing the issue.
