### ISSUE TITLE
Add doubleSeparatorBefore property to application menu configuration

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#343]
The configuration file currently supports `separatorBefore` property.  However, it is also useful to have a double line to indicate higher level grouping of menus.    Therefore, I suggest adding a property `doubleSeparatorBefore`.  As indicated in other issues, this should handle boolean value and quoted boolean value.

**Comment by Nightsphere** [comment]
I have done the push for there new changes. `doubleSeparatorBefore` is now a valid property option just like `separatorBefore`, and will display two horizontal lines in between each dropdown SubMenu. I will leave this open in case there are any small margin/sizing changes that need to happen.

**Comment by smalers** [comment]
The double line separator looks good.  I have also updated the InfoMapper configuration documentation.  I am closing this issue.
