### ISSUE TITLE
Group with one raster that is unselected shows full legend

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#344]
See [District Land Development](http://coagtransfer.openwaterfoundation.org/latest/#/map/baseline-land-development) layer, which has `selectedInitial=False` property set for the layer view.  The legend should be compressed but is displayed.

**Comment by Nightsphere** [comment]
The check for this is done on a string only, and so has been updated with the latest push. It ignores case, and will not display in the legend if the layer is toggled off. Closing the issue.

**Comment by smalers** [comment]
I just pulled the most recent InfoMapper and this is still an issue.  A raster layer that is initially not selected is showing its full legend.  I'm reopening.

![image](https://user-images.githubusercontent.com/6448274/101538219-ffb72f80-3959-11eb-9c71-c2982bf87b84.png)

**Comment by Nightsphere** [comment]
I see where my issue was. I sincerely miss the ignoreCase( ) function in Java, but I'm learning to convert every applicable string to upper case to check between two. The irritating part is that I've already compared dozens of them already in the months past, so I'm slowly learning where there's issues as development goes on, and updating them accordingly. I'll wait to close again until Steve's is working as well.

**Comment by smalers** [comment]
It seems like the code would benefit from something like [StringUtil](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/Util/String/StringUtil.java) where functions like `equalsIgnoreCase` method could be added.  Over time, languages tend to add such things and the need for the utility code goes away.

**Comment by smalers** [comment]
I pulled the current InfoMapper.  It still is not correct.  In this case the layer is now showing up as selected but no legend.  It should be not selected and no legend.

![image](https://user-images.githubusercontent.com/6448274/101553432-d99d8980-3971-11eb-965d-abd0c0dddc78.png)

**Comment by Nightsphere** [comment]
I'm confused, as the code I changed only deals with showing and hiding the legend description and symbol, and checking and unchecking the toggle button. It has nothing to do with displaying the layer. I could reproduce the issue before, but can't now. I'll see what I can do to resolve this.

**Comment by smalers** [comment]
Sorry, my bad.  I was in a hurry and confused the Colorado State Boundary on the bottom with the District Land Development layer.  I'm closing the issue.
