### ISSUE TITLE
Need better error handling for classification files

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#345]
I implemented Burn Area Severity layer group on the Poudre Basin Information website and ran into the following issues.  A console message would be helpful to troubleshoot:

1. If a classification file is given but the `ClassificationAttribute` for the symbol is a bad attribute, everything is drawn in the default color (blue) but there is no warning about the attribute being wrong.
2. If no symbol information is given (no single symbol or classification), the map can have serious problems.  A warning that no symbol is defined would be better rather than current warning message.  Maybe I missed it given the above issue also.

**Comment by Nightsphere** [comment]
An error message should be shown if a geoLayerSymbol, `classificationType` property in the geoLayerSymbol, or the `classificationAttribute` property is not correct. Closing the issue.
