### ISSUE TITLE
Hover not displaying the correct information for Poudre Basin Information

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#347]
**This is critical since it is deployed and I will have to do some work to restore an old version.**

The [Poudre Basin Information](http://poudre.openwaterfoundation.org/1.0.0/#/map/current-wildfires) website is not properly displaying the attributes in the hover.  It seems that it only works for polygons that overlap the raster?  For example, mousing over the East Troublesome polygon and Rocky Mountain National Park polygons shows "CO DWR Water District 3" rather than the proper polygon.  The behavior should be that the popup shows the top-most polygon at the location plus rasters under that location.  Zero or 1 polygon should be in effect at a location.  Zero or more raster bands might be in effect.  Currently I'm only configuring maps with 1 raster, which has 1 band.

**Comment by Nightsphere** [comment]
I pushed some new changes that I believe takes care of the issue. The hovering will act the same as before, with the exception of when both a vector and raster are displayed on the map at the same time. When hovering over a vector that does not have the raster below will now show the vector's popup information only. I'll wait to close this until a bit more testing has been done.

**Comment by smalers** [comment]
This seems to be working well.  I am closing this issue.
