### ISSUE TITLE
Raster layers should not have Data Table kebab menu choice

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#355]
Raster layers should not currently have ***Data Table*** kebab menu.  Trying to use shows a blank popup that does not have a close control.  It is theoretically possible to display a data table.  However, because the height and width of the raster are large, the table would have a large number of rows and columns and be very difficult to scroll.  I suspect that the UI components would choke on it.  We may want to add some other popup tools for rasters in the future, but for now make sure that ***Data Table*** is not available for raster layers.

Similarly, the kebab menu should probably not show ***Clear Selection*** since that functionality is associated with searching in the data table.

**Comment by Nightsphere** [comment]
Data Table will not display for any Raster layers now. Closing the issue.

**Comment by Nightsphere** [comment]
I read the **Clear Selection** comment incorrectly and updated the InfoMapper so that the option will not show up if on a Raster layer. This will be done in the next push I do.
