### ISSUE TITLE
Add README files and reorganize test data

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#357]
I updated the [InfoMapper user documentation](http://software.openwaterfoundation.org/infomapper/latest/doc-user/appendix-install/overview/#file-organization-strategies) to put in place documentation for file organization, which can help Sofia.  I have the following requests for the test data.

1. Add README file to each `assets/app-default` folder explaining the content of the files, with links to appropriate sections of this documentation or GeoProcessor documentation to explain file formats.  Because these files get stripped out during deployment, they won't typically be distributed.  This can help developers (like me) understand file organization and use.
2. The main README or other README needs to be added explaining the nuances of `app` versus `app-default` files.  If the README file should not be deployed, put somewhere that it does not end up in `dist/` for a build,.. maybe the main README.
3. Some files seem to be located in confusing locations.  For example, `data-ts/` seems to contain the documentation files.  I recommend putting the markdown files in the same folder as the related map/layer and have the same name as map/layer, but with `md` file extension.   The `data-ts/` folder should only (or mostly) contain time series files.   See the above link for how I organize graph configurations (I use a `graphs/` folder).  I'm not sure this needs to be used for test data but making it more obvious where the graph configurations live would helop.
4. I suggest renaming `map-template-files` to `map-layer-event-config-files` or something similar to indicate that they are related to event handling.   I use the convention `layer-name-event-config.json`, which makes it easy to know what layer the event configuration is for.  I renamed configuration files to not use "popup" awhile back because we are now using popups for many things.
5. I see Gapminder files.  See the recent discussion about how to coordinate hand-off of such files with InfoMapper.  I recommend putting a script in `build-util` or the `gapminder-data` folder to help with file copies rather than doing a manual copy, with a README.
6. With this organization, how does one know that stray files don't exist?  This could become more of a problem over time.  It is probably not going to be a huge issue but just a thought.  Maybe a script could be written to make sure that data files show up in at least one map configuration?  Use grep.

**Comment by Nightsphere** [comment]
Hmm, I typed out a long message detailing what I updated, but I suppose I never hit the `Comment` button. The quick version is `1-3` has been taken care of, and `app-default` has been updated so that it resembles Steve's file setup.
`4` is not needed since I just put them under the layer folder.
`5` is currently being worked on.
For `6`, I have a folder under `Maps` named `unused-map` that contains all stray files that are not being used anywhere, so that a script could just remove the `unused-map` folder.
