### ISSUE TITLE
How to disable hover event for vector layer

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#362]
In most cases the hover popup default behavior of showing the vector layer on top and then optional raster layers works well.  However, in some cases, this leads to a bad user experience.  For example, consider the following:

[Land Development](http://coagtransfer.openwaterfoundation.org/latest/#/map/baseline-land-development)

In this case the vector layer is for the State of Colorado but the information provided to the user has minimal value and makes it more difficult to visually locate the raster data values in the popup.   In this case, need a way to disable the output for the hover popup.  Would this be specified on the GeoLayerView?  Need input from Josh on some ideas.  We don't want to require this in configuration because that would add a lot more work.  We just want to specify a property when needed to disable the default behavior.

Maybe something like `enabledForHover` true/false?

**Comment by Nightsphere** [comment]
The changes for this have been merged. There is now a `enabledForHover` property option in each geoLayerView. If set to False (e.g. `enabledForHover: "False"`), the div will not be updated with the layer's data and won't show up on the map, freeing up space and making it easier to read for other layers. I believe the issue has been taken care of, and can be reopened if problems persist. Closing the issue.
