### ISSUE TITLE
Include formatting features for properties in text

### ISSUE THREAD

**Issue by jurentie** [OpenWaterFoundation/owf-app-infomapper-ng#37]
There are of course going to be issues to deal with such as how to handle nulls and other missing values, precision for floating point numbers, etc. One way that I have handled this in TSTool is to add formatting functions that can be changed, such as the following, which allow inlining more advanced formatting.

```
${feature:capacity}.round(2)
```

It may also be helpful to have a default behavior such as formatting all feature properties. In this case there will need to be a way to indicate the formatting, maybe use auto as the text string and then the code can detect and do its own default formatting, such as listing all feature attributes. Requiring configuration other than a blank string makes sure it is obvious what is being done.

**Comment by smalers** [comment]
Features have recently been implemented to format properties with `.toMixedCase()` and `.replace()`.  Circle around on other modifiers when the event handling redesign is implemented.

**Comment by smalers** [comment]
Close this issue.  New issues can be added if necessary.
