### ISSUE TITLE
For Markdown pages, position scrollbar on far right.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#376]
Markdown/showdown pages are width-sized to have a reasonable text area.  For wide-screeen monitors using the full width for the text is overwhelming visually.  Therefore, a somewhat narrower page size consistent with hard-copy print is often used, and is the case with InfoMapper.

However, if the page content is longer than can fit on the screen, a vertical scrollbar is shown on the right side of text.  This is also needed because of the sticky menus across the top of the application.  The scrollbar is somewhat ugly in that it is not on the far right, where a normal browser scrollbar would be positioned.

Is it possible to format text so that it still has the desired width, but have the scroll bar on the far right as if the browser scroll bar?  For example, can a padding be added between the right edge of the text to force the scroll bar to shift to the right edge of the window?  This would achieve the desired result of text on only part of the width, and scroll bar on far right of the window.  The the scrollbar won't be so distracting reading the text.  This would need to work with all elements in a markdown/showdown page.

**Comment by Nightsphere** [comment]
A Content Page's scrollbar will now be displayed on the far right of the page, and will have more intelligence on correctly displaying for different vertical sizes of a screen it's on. Closing the issue.
