### ISSUE TITLE
Disable action when main menus are clicked on

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#379]
Clicking on the main menu items in the Poudre Basin Information website causes the main page to display.  This is irritating.  There are currently no content associated with the main menu items since only sub-menus have content.  Some ideas are:

1. Disable events by default on the main menus.
2. Allow a property in the app configuration file to disable events.
3. Allow action on the main menu item, such as content page that explains the menu.  This would require some properties in the application configuration file similar to other menus.  It might be a good idea to provide a documentation page for each main menu item.

**Comment by Nightsphere** [comment]
The main menus have been changed from `<a>` tags to `<button>`'s. This has allowed me to tell them to do nothing on a click. A ripple effect will occur, but nothing will actually happen. I'm looking into changing the submenu's to these as well, mainly just for consistency's sake. Closing this issue.
