### ISSUE TITLE
Poudre Basin Information location of ts is broken

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#382]
The Poudre Basin Information graphs were broken.  The graph is looking for time series under `latest/assets/ts` (`latest` is the installation folder).  They should be under the `ts` folder associated with the map.  The scoping of relative paths is not working somehow.  I suspect that the plotting library code needs better information for where "home" is for relative data path expansion.  Need to be careful not to have one global setting.

I worked around by copying data to the necessary folder in S3 but this needs to be fixed.

We also need a way to run automated tests on production systems to make sure things are working OK.  Now that libraries are being used, some things seem fragile and are discovered at the worst times (like an hour before a presentation).

**Comment by Nightsphere** [comment]
The commit has been merged, and the new path resolver should take care of all paths being passed from the app to the common library, absolute or relative. I'll wait a bit to close the issue.

**Comment by Nightsphere** [comment]
This has been working for a while now. Closing the issue.
