### ISSUE TITLE
Showdown CSS for bullets is wrong?

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#387]
The CSS for top level bullets for markdown/showdown seems wrong.  It is showing in bold when it should be normal font?  If the author wants bold they can define that themselves.  I don't know if there are other formatting things that should be changed.

**Comment by Nightsphere** [comment]
I believe this was fixed months ago, and I cannot recreate. It can be opened up again if the problem is found again. Closing the issue.
