### ISSUE TITLE
Search layer data polygon highlight properties need clarification

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#397]
Highlighting for mouse-over is optional.  Highlighting for filtered/selected features from data table is an additional visual technique.  This is what Josh said about highlighting:

----

As for the highlighting, the highlightEnabled property only affects a mouseover highlight. To enable it, use
"highlightEnabled": "true" under geoLayerView properties. The highlighting of a feature is its own contained
component, and will now highlight by filtering through the search bar by default; you won't have to do anything else for that to
work. Let me know if something else needs to be looked at and/or changed!

----

I'm not highlighting on mouse-over (yet).  When I search the municipal boundaries using the data table I see the following (note Fort Collins highlighted in blue and not yellow).  I'm just wondering if this is the designed behavior.  We may need another property for highlight when selected (compared to mouseover).  I thought Josh said that yellow should be used here also?  I need clarification.

![image](https://user-images.githubusercontent.com/6448274/118325971-7fc16280-b4c1-11eb-9a2a-048b5ca9d907.png)

**Comment by smalers** [comment]
Hmmm.... I then tried to filter by address and used my home address.  This does seem to highlight in yellow.  When I used the ***Clear selection*** menu for the layer, the yellow polygon went away but the blue highlight remains.  It seems like there is a difference in behavior of highlighting selected when using layer data or address.  I think highlight color for selected should be the same in either case (yellow).  And, clearing selections need to fully clear regardless of how many times ***Enter*** was used on the data table.  I'm going to reload and try going to search by address first.

**Comment by smalers** [comment]
I am testing using a new layer, which merges boundaries from different sources.  This is what I am going to base my presentation on for Go Code Colorado later today.

[http://poudre.openwaterfoundation.org/2.2.0/#/map/entities-water-providers](http://poudre.openwaterfoundation.org/2.2.0/#/map/entities-water-providers)

Also, the highlight color in yellow is too opaque and makes it difficult to read the background layer.  Is there a map configuration property that I can change to adjust the opacity.  Or, maybe just change the global default for now.  See the following image for example.  Hopefully the combination of The good news is that I was able to search for my house now.

Also, turning off the layer should also turn off the selected features for the layer.  Currently, turning off the layer shows the yellow selected features, which is how I can tell that opacity is too high (not transparent enough).  I can work around this, but it would be good if capacity is better.  We'll probably need to sort out the select colors more.

![image](https://user-images.githubusercontent.com/6448274/118410319-086c0a00-b64c-11eb-88fd-2f97162c7420.png)

**Comment by Nightsphere** [comment]
The common library's version has been updated to 0.1.2. I brought the highlighted opacity down from `0.7` to `0.4`. I've also updated the MapLayerItem class so that when a layer is toggled off and on, the selected layer will follow suit.

This should be good for testing now. I'm still looking into displaying a marker on an address. Adding it has been fine, but I still need to look into how/when it will be removed.

**Comment by smalers** [comment]
I did a `git pull` for InfoMapper and then `npm install` and see the following.  Thinking that something might be slow, I tried again and got the same error.

```
sam (master) infomapper $ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @OpenWaterFoundation/common@0.1.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'infomapper'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sam\AppData\Roaming\npm-cache\_logs\2021-05-17T03_00_25_111Z-debug.log
```

**Comment by Nightsphere** [comment]
The `npm publish` command got to the very last line and then did nothing, so it looks like it never actually published. I killed it, ran it again and it successfully updated. It should be okay now. I will refrain from sending a message until I know for sure everything is ready to go. It should be good now.

**Comment by smalers** [comment]
Make sure that scripts check for exit status of previous command using something like the following, which can help detect problems.

```
if [ $? -ne 0 ]; then
    # Error in previous command.
fi
```

**Comment by smalers** [comment]
OK, the section colors are good for everything I tried.  We may modify slightly later but OK for now.  The "zoom to" and "clear selection" features also seem to be OK.  I'll do what I can with the current features to create the video I need tonight and tomorrow maybe the marker feature will be available for the Go Code Colorado application on Tuesday.

For example, with the current data that I am using, the office address shows up with 2 water providers, I assume because of complex boundaries.  It would be great to have the market to illustrate why that is occurring.  I'll send the GeoJSON in case you want to try.

**Comment by smalers** [comment]
One use case that is currently not working is as follows, where the data table remains open the entire time.

1. Do an address query.
2. Zoom to address or selected features.  The marker is shown.
3. Clear selected features
4. Press enter again... nothing selects.
5. Change the address slightly, such as remove/add the zip code.  Press enter.  The feature and marker are shown on the map.

There needs to be logic to handle the case that a user cleared selections and then re-entered the same select again.  This is different from a user entering the same select repeatedly but not clearing selection between.

**Comment by Nightsphere** [comment]
The issue brought up in the previous comment is currently working in both the testing environment, and on the Poudre Basin website, which is using version 2.x. Closing the issue.
