### ISSUE TITLE
Long legend strings overflow

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#402]
Long legend strings overflow.  It would be good if the text was always to the right of the legend symbol.  See below.

[http://poudre.openwaterfoundation.org/latest/#/map/entities-basins](http://poudre.openwaterfoundation.org/latest/#/map/entities-basins)

![image](https://user-images.githubusercontent.com/6448274/118790153-bb0db980-b852-11eb-9127-c3452d2bf2f2.png)

**Comment by Nightsphere** [comment]
This has been fixed and will be implemented in the next Common library release. Closing the issue.
