### ISSUE TITLE
Feedback on README

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#410]
I used a clean clone of InfoMapper for the StateMod dataset viewer and have some comments on the README, attached.

[infomapper-notes.md](https://github.com/OpenWaterFoundation/owf-app-infomapper-ng/files/6887247/infomapper-notes.md)

**Comment by Nightsphere** [comment]
This had already been taken care of and added to the README file. Closing the issue.
