### ISSUE TITLE
Error displaying graph

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#411]
I have an error displaying a Reservoir Summary graph.  Attached is the console output.  Maybe just needs better error handling.  I'll have to spend a bit more time cleaning up. 

The [old website](http://opencdss.openwaterfoundation.org/datasets/colorado/2015/#/map/cm2015-historical) shows blank window. I don't recall if this is a bug that was never resolved.  I can look at the inputs again but see if there is something obvious in the code.

![image](https://user-images.githubusercontent.com/6448274/127193089-d29e398f-131c-4d3e-9124-732de5f69132.png)

**Comment by Nightsphere** [comment]
This was the InfoMapper app using the Common package incorrectly. It has since been resolved, and the graph will display. Closing the issue.
