### ISSUE TITLE
Customizable generic page

### ISSUE THREAD

**Issue by jurentie** [OpenWaterFoundation/owf-app-infomapper-ng#45]
In relation to the previous issue #44, it would be convenient to create a generic page component where users can configure a markdown file and that can be displayed on a generic page that can be configured to be linked to from the navigation bar.

**Comment by Nightsphere** [comment]
Generic pages are now content pages, and the core functionality of this issue has been taken care of. Issues have already been created for the future planning comment above. Closing this issue.
