### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by jurentie** [OpenWaterFoundation/owf-app-infomapper-ng#52]
Since restructuring much of the code while working on issue #45, the documentation needs to be updated to reflect new components and removed components, as well as how all the components link together.

**Comment by Nightsphere** [comment]
This issue is old and broad. Documentation should always be updated and added to as more work on the Infomapper is completed, and more granular issues can be created if new sections of the documentation need to be created or changed. Closing this issue.
