### ISSUE TITLE
Explain what package-lock.json is and why in the repo.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#63]
I am not doing active development on the application.  However, somehow my actions result in the following file changing:

```
poudre-dashboard-ng/package-lock.json
```

What is this file?  Should it be gitignored?  I usually run `git checkout -- filename` to remove the local change.  I'm assuming that this file is updated to reflect dependency versions.  It seems that we need a clear decision about whether one developer commits this file and others respond to it, or it is generated by each developer and not committed to the repository.  We can't have developers flip-flopping the content of this file and stepping on each other.

**Comment by Nightsphere** [comment]
The `package-lock.json` section has been added to the infomapper-doc-dev at **Development Environment / Node.js**. I'm not providing a link because it has not been pushed to AWS yet, but will be soon. Closing this issue.
